services:
  app:
    build:
      context: .
    container_name: express-app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=supersecretkey
      - DB_NAME=skills5
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=mysql
      - DB_DIALECT=mysql
    depends_on:
      - mysql
    volumes:
      - sqlite-data:/app/database

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: skills5
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  sqlite-data:
  mysql-data:
