version: '3.8'

services:

  db:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monapp
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      retries: 10

  app:
    build: .
    container_name: app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: monapp
      MATOMO_TOKEN: ${MATOMO_TOKEN}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MAILGUN_KEY: ${MAILGUN_KEY}
      MAIL_KEY: ${MAIL_KEY}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
    depends_on:
      db:
        condition: service_healthy

  matomo:
    image: matomo:latest
    container_name: matomo
    restart: always
    ports:
      - "8080:80"
    environment:
      MATOMO_DATABASE_HOST: db
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: matomo_
      MATOMO_DATABASE_USERNAME: root
      MATOMO_DATABASE_PASSWORD: root
      MATOMO_DATABASE_DBNAME: matomo
      MATOMO_TOKEN: ${MATOMO_TOKEN}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - matomo_data:/var/www/html

volumes:
  db_data:
  matomo_data:
