version: '3.8'

services:

  backend:
    container_name: express-backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - sqlite-data:/app/database
    environment:
      - PORT=5000
      - JWT_SECRET=supersecretkey
    depends_on:
      - frontend

  frontend:
    container_name: react-frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://localhost:5000/api
    command: npm run dev

volumes:
  sqlite-data:
